test_root=/org/lenze/nupano/suite
suite_repoistory=/resources/repository/suiterepository.json
suite_id=sdcb-319
active_stage=
element_load_time=30
azureb2c_clientId=20fea690-0a64-4a1e-9502-7b52c55f2bab
azureb2c_tenant_root=mylenze-dev.lenze.com
azureb2c_tenant=lenzeb2cdev.onmicrosoft.com
azureb2c_policy=b2c_1a_signup_signin
azureb2c_redirectUri=http://localhost:3256
azureb2c_scope=profile 20fea690-0a64-4a1e-9502-7b52c55f2bab
nupanosuite_password=Dozu967829
nupanosuite_user=
azureb2c_accesstoken=
azureb2c_tokenID=
nupanosuite_url=https://auto-test.account.dev.engineering-suite.lenze.com
content_type=
azureB2CAuthenticationType=UI
